route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord_slack

receivers:
  - name: discord_slack
    discord_configs:
      - webhook_url: 'DISCORD_URL'

    slack_configs:
      - api_url: 'SLACK_URL'
        send_resolved: true
        channel: '#monitoramento-sistemas'
        text: "{{ .CommonAnnotations.summary }}\n*Description:* {{ .CommonAnnotations.description }}\n*Severity:* {{ .CommonLabels.severity }}\n*Instance:* {{ .CommonLabels.instance }}\n[Ver AlertManager]({{ .ExternalURL }})"
    
    webhook_configs:
      - url: 'http://calert:6000/dispatch'