[app]
address = "0.0.0.0:6000"
server_timeout = "60s"
enable_request_logs = true
log = "info"

[providers.discord_slack_calert]
type = "google_chat"
endpoint = "GoogleChatWebhookURL"
max_idle_conns =  50
timeout = "30s"
# proxy_url = "http://internal-squid-proxy.com:3128"
template = "static/message.tmpl"
thread_ttl = "12h"
threaded_replies = true
dry_run = false