[app]
address = "0.0.0.0:6000" # Address of the HTTP Server.
server_timeout = "60s" # Server timeout for HTTP requests.
enable_request_logs = true # Whether to log incoming HTTP requests or not.
log = "info" # Use `debug` to enable verbose logging. Can be set to `info` otherwise.

[providers.discord_slack_calert]
type = "google_chat" # Type of provider. Currently supported value is `google_chat`.
endpoint = "https://chat.googleapis.com/v1/spaces/AAAAHVIWbrQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=lbXlO2EFge1PnjZWI_Cos5Bdn4nWKcDuKyaFBqo79Yc" # Google Chat Webhook URL
max_idle_conns =  50 # Max idle connections in the HTTP Client.
timeout = "30s" # Timeout for making requests to Provider.
# proxy_url = "http://internal-squid-proxy.com:3128" # Specify `proxy_url` as your proxy endpoint to route all HTTP requests to the provider via a proxy.
template = "static/message.tmpl" # Path to specify the message template path.
thread_ttl = "12h" # Timeout to keep active alerts in memory. Once this TTL expires, a new thread will be created.
threaded_replies = true # Whether to send threaded replies or not.
dry_run = false