networks:
  monit:
    external: true

volumes:
  prometheus:

services:
  prometheus-hml:
    image: prom/prometheus:latest
    container_name: prometheus-hml
    user: "1000:1000"
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
     #- ./prometheus/alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monit
    #depends_on:
    #  - proxy-hml

  #alertmanager-hml: 
    #image: prom/alertmanager
    #container_name: alertmanager-hml
    #volumes: 
    #  - ./alertmanager:/etc/alertmanager/:ro
    #ports: 
    #  - 9093:9093
    #command: 
    #  - --config.file=/etc/alertmanager/alertmanager.yml
    #networks:
    #  - monit
    #depends_on:
    #  - prometheus-hml

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  grafana-hml:
    image: grafana/grafana
    container_name: grafana-hml
    user: "1000:1000"
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monit
    depends_on:
      - prometheus-hml
