global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alert.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['172.17.0.1:9100']

- job_name: prometheus
  metrics_path: /prometheus/metrics
  static_configs:
  - targets: ['prometheus:9090']

- job_name: cadvisor
  metrics_path: /metrics
  scrape_interval: 30s
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: docker
  scrape_interval: 30s
  static_configs:
  - targets: ['172.17.0.1:9323']